const now = '2026-06-09 20:30:00'

export const mockCategories = [
  { id: 1, name: '电子产品', sortOrder: 1, status: 1, itemCount: 18, createTime: now },
  { id: 2, name: '校园卡证', sortOrder: 2, status: 1, itemCount: 24, createTime: now },
  { id: 3, name: '书籍资料', sortOrder: 3, status: 1, itemCount: 12, createTime: now },
  { id: 4, name: '生活用品', sortOrder: 4, status: 1, itemCount: 9, createTime: now },
  { id: 5, name: '衣物配饰', sortOrder: 5, status: 1, itemCount: 7, createTime: now },
]

export const mockUsers = [
  {
    id: 1,
    username: 'student001',
    nickname: '张三',
    phone: '13800000000',
    email: 'student001@example.com',
    avatar: '',
    role: 'USER',
    status: 1,
    lastLoginTime: now,
    createTime: '2026-06-01 09:00:00',
  },
  {
    id: 2,
    username: 'admin',
    nickname: '管理员',
    phone: '13900000000',
    email: 'admin@example.com',
    avatar: '',
    role: 'ADMIN',
    status: 1,
    lastLoginTime: now,
    createTime: '2026-05-28 09:00:00',
  },
]

export const mockItems = [
  {
    id: 10,
    userId: 1,
    publisherId: 1,
    title: '捡到一部黑色手机',
    itemType: 'FOUND',
    categoryId: 1,
    categoryName: '电子产品',
    location: '图书馆二楼自习区',
    eventTime: '2026-06-09 18:20:00',
    status: 'AVAILABLE',
    expireTime: '2026-07-09 18:20:00',
    viewCount: 128,
    claimCount: 2,
    publisherName: '张三',
    description: '黑色手机，透明保护壳，屏幕壁纸像是校园湖边照片。',
    contactInfo: '13800000000',
    isPublicContact: 0,
    createTime: '2026-06-09 20:00:00',
    imageUrls: [],
    coverImage: '',
  },
  {
    id: 11,
    userId: 3,
    publisherId: 3,
    title: '丢失蓝色校园卡',
    itemType: 'LOST',
    categoryId: 2,
    categoryName: '校园卡证',
    location: '一食堂到教学楼 A 座路上',
    eventTime: '2026-06-08 12:10:00',
    status: 'AVAILABLE',
    expireTime: '2026-06-30 23:59:59',
    viewCount: 86,
    claimCount: 0,
    publisherName: '李四',
    description: '蓝色卡套，卡面姓名李同学，内有一张门禁卡。',
    contactInfo: '13600000001',
    isPublicContact: 1,
    createTime: '2026-06-08 12:30:00',
    imageUrls: [],
    coverImage: '',
  },
  {
    id: 12,
    userId: 4,
    publisherId: 4,
    title: '拾到高等数学教材',
    itemType: 'FOUND',
    categoryId: 3,
    categoryName: '书籍资料',
    location: '教学楼 B303',
    eventTime: '2026-06-07 16:40:00',
    status: 'CLAIMING',
    expireTime: '2026-07-07 16:40:00',
    viewCount: 43,
    claimCount: 1,
    publisherName: '王同学',
    description: '高等数学下册，扉页写有课程分组编号。',
    contactInfo: 'wang@example.com',
    isPublicContact: 0,
    createTime: '2026-06-07 17:10:00',
    imageUrls: [],
    coverImage: '',
  },
  {
    id: 13,
    userId: 1,
    publisherId: 1,
    title: '丢失灰色雨伞',
    itemType: 'LOST',
    categoryId: 4,
    categoryName: '生活用品',
    location: '体育馆看台',
    eventTime: '2026-06-04 19:00:00',
    status: 'PENDING_REVIEW',
    expireTime: '2026-07-04 19:00:00',
    viewCount: 0,
    claimCount: 0,
    publisherName: '张三',
    description: '折叠伞，伞柄上贴了姓名贴。',
    contactInfo: '13800000000',
    isPublicContact: 0,
    createTime: '2026-06-04 20:12:00',
    imageUrls: [],
    coverImage: '',
  },
  {
    id: 14,
    userId: 5,
    publisherId: 5,
    title: '拾到白色无线耳机盒',
    itemType: 'FOUND',
    categoryId: 1,
    categoryName: '电子产品',
    location: '操场北门',
    eventTime: '2026-05-28 21:20:00',
    status: 'EXPIRED',
    expireTime: '2026-06-05 21:20:00',
    viewCount: 57,
    claimCount: 0,
    publisherName: '赵同学',
    description: '白色耳机充电盒，外壳有一道划痕。',
    contactInfo: '13700000002',
    isPublicContact: 0,
    createTime: '2026-05-28 22:00:00',
    imageUrls: [],
    coverImage: '',
  },
]

export const mockClaims = [
  {
    id: 5,
    itemId: 10,
    itemTitle: '捡到一部黑色手机',
    publisherId: 1,
    applicantId: 3,
    applicantName: '李四',
    applicantPhone: '13800000001',
    claimDesc: '这是我下午在图书馆丢失的手机。',
    proofInfo: '透明壳，锁屏壁纸是校园照片。',
    lostTime: '2026-06-09 17:50:00',
    lostLocation: '图书馆二楼',
    featureDesc: '机身背面贴有课程群二维码贴纸。',
    status: 'PENDING',
    reviewRemark: '',
    supplementDeadline: '',
    createTime: '2026-06-09 20:10:00',
    evidenceUrls: [],
  },
  {
    id: 6,
    itemId: 12,
    itemTitle: '拾到高等数学教材',
    publisherId: 4,
    applicantId: 1,
    applicantName: '张三',
    applicantPhone: '13800000000',
    claimDesc: '教材应该是我的。',
    proofInfo: '扉页写了我的分组编号。',
    lostTime: '2026-06-07 15:50:00',
    lostLocation: '教学楼 B303',
    featureDesc: '书里夹着蓝色便利贴。',
    status: 'NEED_MORE',
    reviewRemark: '请补充扉页姓名或购买记录。',
    supplementDeadline: '2026-06-12 23:59:59',
    createTime: '2026-06-07 18:10:00',
    evidenceUrls: [],
  },
]

export const mockHandovers = [
  {
    id: 20,
    itemId: 12,
    itemTitle: '拾到高等数学教材',
    publisherName: '王同学',
    applicantName: '张三',
    appointmentTime: '2026-06-10 17:30:00',
    appointmentLocation: '图书馆一楼服务台',
    handoverCode: 'LLC-482913',
    status: 'WAIT_CONFIRM',
    createTime: '2026-06-09 12:00:00',
    remark: '',
  },
]

export const mockNotices = [
  { id: 1, title: '认领申请需要补充材料', content: '高等数学教材的认领申请需要补充证明。', type: 'CLAIM', readFlag: 0, bizId: 6, createTime: now },
  { id: 2, title: '发布审核通过', content: '黑色手机拾物信息已公开展示。', type: 'ITEM', readFlag: 1, bizId: 10, createTime: '2026-06-09 20:05:00' },
]

export const mockLogs = [
  { id: 1, userId: 2, module: '物品审核', operation: '审核通过物品', requestMethod: 'POST', requestUrl: '/api/admin/items/10/approve', ipAddress: '127.0.0.1', resultStatus: 'SUCCESS', createTime: now },
  { id: 2, userId: 2, module: '认领审核', operation: '要求补充材料', requestMethod: 'POST', requestUrl: '/api/admin/claims/6/need-more', ipAddress: '127.0.0.1', resultStatus: 'SUCCESS', createTime: now },
]

export const pageOf = (records) => ({ total: records.length, pageNum: 1, pageSize: 10, records })

export const dashboardSummary = {
  totalItemCount: 68,
  pendingItemCount: 7,
  pendingClaimCount: 4,
  claimedCount: 19,
  todayNewCount: 8,
  expiredCount: 5,
}

export const mockTimeline = [
  { id: 1, title: '发布信息', status: 'DONE', operatorName: '用户', createTime: '2026-06-09 20:00:00', remark: '提交发布信息' },
  { id: 2, title: '管理员审核', status: 'CURRENT', operatorName: '管理员', createTime: now, remark: '等待审核或已进入展示' },
  { id: 3, title: '在线认领', status: 'WAIT', operatorName: '系统', createTime: '', remark: '失主提交认领申请' },
  { id: 4, title: '预约交接', status: 'WAIT', operatorName: '双方', createTime: '', remark: '线下完成交接' },
]
